name = "visitarandomwebsite"
main = "dist/_worker.js/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-29"

[site]
bucket = './dist'

[[d1_databases]]
binding = "DB"
database_name = "visitarandomwebsite"
database_id = "08e35040-8a13-446f-a68a-c4e2a266db77"
preview_database_id = "DB" 